all: ArrayListS1 ArrayListS2 ArrayListS3 ArrayListS4 LinkedListS1 LinkedListS2 LinkedListS3 LinkedListS4 LDLinkedListS1 LDLinkedListS2 LDLinkedListS3 LDLinkedListS4 clean

ArrayListS1: ArrayList/main/*/*.java ArrayList/tests/Scenario1.java
	@javac ArrayList/tests/Scenario1.java
	@java ArrayList/tests/Scenario1

ArrayListS2: ArrayList/main/*/*.java ArrayList/tests/Scenario2.java
	@javac ArrayList/tests/Scenario2.java
	@java ArrayList/tests/Scenario2

ArrayListS3: ArrayList/main/*/*.java ArrayList/tests/Scenario3.java
	@javac ArrayList/tests/Scenario3.java
	@java ArrayList/tests/Scenario3

ArrayListS4: ArrayList/main/*/*.java ArrayList/tests/Scenario4.java
	@javac ArrayList/tests/Scenario4.java
	@java ArrayList/tests/Scenario4
	
	
LinkedListS1: LinkedList/main/*/*.java LinkedList/tests/Scenario1.java
	@javac LinkedList/tests/Scenario1.java
	@java LinkedList/tests/Scenario1
	
LinkedListS2: LinkedList/main/*/*.java LinkedList/tests/Scenario2.java
	@javac LinkedList/tests/Scenario2.java
	@java LinkedList/tests/Scenario2
	
LinkedListS3: LinkedList/main/*/*.java LinkedList/tests/Scenario3.java
	@javac LinkedList/tests/Scenario3.java
	@java LinkedList/tests/Scenario3
	
LinkedListS4: LinkedList/main/*/*.java LinkedList/tests/Scenario4.java
	@javac LinkedList/tests/Scenario4.java
	@java LinkedList/tests/Scenario4
	
	
LDLinkedListS1: LDLinkedList/main/*/*.java LDLinkedList/tests/Scenario1.java
	@javac LDLinkedList/tests/Scenario1.java
	@java LDLinkedList/tests/Scenario1
 
LDLinkedListS2: LDLinkedList/main/*/*.java LDLinkedList/tests/Scenario2.java
	@javac LDLinkedList/tests/Scenario2.java
	@java LDLinkedList/tests/Scenario2

LDLinkedListS3: LDLinkedList/main/*/*.java LDLinkedList/tests/Scenario3.java
	@javac LDLinkedList/tests/Scenario3.java
	@java LDLinkedList/tests/Scenario3

LDLinkedListS4: LDLinkedList/main/*/*.java LDLinkedList/tests/Scenario4.java
	@javac LDLinkedList/tests/Scenario4.java
	@java LDLinkedList/tests/Scenario4
	
	
clean:
	@rm -f */*/*/*.class
	@rm -f */tests/*.class
	
	
